/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "中国保安协会",
  "tagline": "中国保安协会",
  "organizationName": "543x",
  "projectName": "中国保安协会",
  "baseUrl": "/",
  "baseUrlIssueBanner": true,
  "url": "https://www.123j.com",
  "trailingSlash": false,
  "stylesheets": [
    {
      "href": "/katex/katex.min.css",
      "type": "text/css"
    }
  ],
  "i18n": {
    "defaultLocale": "zh",
    "locales": [
      "zh"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "format": "detect",
    "mermaid": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "remarkRehypeOptions": {
      "footnoteLabel": "Footnotes"
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "onBrokenLinks": "ignore",
  "onBrokenAnchors": "ignore",
  "onBrokenMarkdownLinks": "ignore",
  "favicon": "img/logobaidu.webp",
  "staticDirectories": [
    "static",
    "C:\\Users\\Administrator\\Desktop\\English\\website\\_dogfooding\\_asset-tests",
    "C:\\Users\\Administrator\\Desktop\\English\\website\\_dogfooding\\non-existent"
  ],
  "themes": [
    "live-codeblock",
    null
  ],
  "plugins": [
    null,
    [
      "content-docs",
      {
        "id": "community",
        "path": "community",
        "routeBasePath": "community",
        "editUrl": "https://github.com/teabagging/security/edit/main/website",
        "remarkPlugins": [
          null
        ],
        "editCurrentVersion": true,
        "sidebarPath": "./sidebarsCommunity.js",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true
      }
    ],
    [
      "content-docs",
      {
        "id": "google",
        "path": "google",
        "routeBasePath": "google",
        "editUrl": "https://github.com/teabagging/security/edit/main/website",
        "remarkPlugins": [
          null
        ],
        "editCurrentVersion": true,
        "sidebarPath": "./sidebars.ts",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true
      }
    ],
    [
      "content-docs",
      {
        "id": "learn",
        "path": "learn",
        "routeBasePath": "learn",
        "editUrl": "https://github.com/teabagging/security/edit/main/website",
        "remarkPlugins": [
          null
        ],
        "editCurrentVersion": true,
        "sidebarPath": "./sidebars.ts",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true
      }
    ],
    [
      "client-redirects",
      {
        "fromExtensions": [
          "html"
        ],
        "redirects": [
          {
            "from": [
              "/docs/support",
              "/docs/next/support"
            ],
            "to": "/community/support"
          },
          {
            "from": [
              "/home/"
            ],
            "to": "/"
          },
          {
            "from": [
              "/home/qs"
            ],
            "to": "/?a=1"
          },
          {
            "from": [
              "/home/anchor"
            ],
            "to": "/#anchor"
          },
          {
            "from": [
              "/home/absolute"
            ],
            "to": "https://docusaurus.io/"
          },
          {
            "from": [
              "/home/absolute/qs"
            ],
            "to": "https://docusaurus.io/?a=1"
          },
          {
            "from": [
              "/home/absolute/anchor"
            ],
            "to": "https://docusaurus.io/#anchor"
          }
        ]
      }
    ],
    [
      "ideal-image",
      {
        "quality": 70,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": true
      }
    ],
    [
      "pwa",
      {
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "swCustom": "C:\\Users\\Administrator\\Desktop\\English\\website\\src\\sw.js",
        "pwaHead": [
          {
            "tagName": "link",
            "rel": "icon",
            "href": "img/logobaidu.webp"
          },
          {
            "tagName": "link",
            "rel": "manifest",
            "href": "manifest.json"
          },
          {
            "tagName": "meta",
            "name": "theme-color",
            "content": "rgb(37, 194, 160)"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-capable",
            "content": "yes"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-status-bar-style",
            "content": "#000"
          },
          {
            "tagName": "link",
            "rel": "apple-touch-icon",
            "href": "img/logobaidu.webp"
          },
          {
            "tagName": "link",
            "rel": "mask-icon",
            "href": "img/logobaidu.webp",
            "color": "rgb(62, 204, 94)"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileImage",
            "content": "img/logobaidu.webp"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileColor",
            "content": "#000"
          }
        ]
      }
    ],
    "@docusaurus/theme-mermaid",
    "./src/plugins/featureRequests/FeatureRequestsPlugin.js",
    [
      "content-docs",
      {
        "id": "docs-tests",
        "routeBasePath": "/tests/docs",
        "sidebarPath": "_dogfooding/docs-tests-sidebars.js",
        "versions": {
          "current": {
            "noIndex": true
          }
        },
        "onInlineTags": "warn",
        "tags": "tags.yml",
        "recmaPlugins": [
          [
            null,
            null
          ]
        ],
        "path": "_dogfooding/_docs tests",
        "showLastUpdateTime": true,
        "showLastUpdateAuthor": true
      }
    ],
    [
      "@docusaurus/plugin-content-blog",
      {
        "id": "blog-tests",
        "path": "_dogfooding/_blog tests",
        "routeBasePath": "/tests/blog",
        "editUrl": "https://github.com/facebook/docusaurus/edit/main/website/_dogfooding/_blog-tests",
        "postsPerPage": 3,
        "blogSidebarCount": "ALL",
        "feedOptions": {
          "type": "all",
          "title": "Docusaurus Tests Blog",
          "copyright": "Copyright © 2025 Facebook, Inc.",
          "xslt": {
            "rss": "custom-rss.xsl",
            "atom": "custom-atom.xsl"
          }
        },
        "onInlineTags": "warn",
        "onInlineAuthors": "ignore",
        "onUntruncatedBlogPosts": "ignore",
        "tags": "tags.yml"
      }
    ],
    [
      "C:\\Users\\Administrator\\Desktop\\English\\website\\node_modules\\@docusaurus\\plugin-content-pages\\lib\\index.js",
      {
        "id": "pages-tests",
        "path": "_dogfooding/_pages tests",
        "routeBasePath": "/tests/pages",
        "showLastUpdateTime": true,
        "showLastUpdateAuthor": true
      }
    ],
    null
  ],
  "presets": [
    [
      "classic",
      {
        "debug": true,
        "blog": {
          "path": "blog",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "editUrl": "https://github.com/teabagging/security/edit/main/website",
          "remarkPlugins": [
            null
          ],
          "postsPerPage": 5,
          "feedOptions": {
            "type": "all",
            "description": "Bible",
            "copyright": "Copyright © 2025 Bible, Inc.",
            "xslt": true
          },
          "blogTitle": " blog",
          "blogDescription": "web and native user interfaces.",
          "blogSidebarCount": "ALL",
          "blogSidebarTitle": "All our posts",
          "onUntruncatedBlogPosts": "warn",
          "onInlineTags": "warn"
        },
        "pages": {
          "remarkPlugins": [
            null
          ],
          "editUrl": "https://github.com/teabagging/security/edit/main/website",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true
        },
        "theme": {
          "customCss": [
            "./src/css/custom.css",
            "./_dogfooding/dogfooding.css"
          ]
        },
        "gtag": {
          "trackingID": [
            "G-E5CR2Q1NRE"
          ]
        },
        "sitemap": {
          "ignorePatterns": [
            "/tests/{blog,pages}/**"
          ],
          "lastmod": "date",
          "priority": null,
          "changefreq": null
        }
      }
    ]
  ],
  "themeConfig": {
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "announcementBar": {
      "id": "announcementBar}",
      "content": "🎉️ <b><a target=\"_blank\" href=\"https://www.543x.com\">www.543x.com</a> is out!</b> 🥳️",
      "isCloseable": true
    },
    "prism": {
      "additionalLanguages": [
        "java",
        "latex",
        "haskell",
        "matlab",
        "php",
        "powershell",
        "bash",
        "diff",
        "json",
        "scss"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "This will error"
        }
      ],
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          },
          {
            "types": [
              "title"
            ],
            "style": {
              "color": "#0550AE",
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "parameter"
            ],
            "style": {
              "color": "#953800"
            }
          },
          {
            "types": [
              "boolean",
              "rule",
              "color",
              "number",
              "constant",
              "property"
            ],
            "style": {
              "color": "#005CC5"
            }
          },
          {
            "types": [
              "atrule",
              "tag"
            ],
            "style": {
              "color": "#22863A"
            }
          },
          {
            "types": [
              "script"
            ],
            "style": {
              "color": "#24292E"
            }
          },
          {
            "types": [
              "operator",
              "unit",
              "rule"
            ],
            "style": {
              "color": "#D73A49"
            }
          },
          {
            "types": [
              "font-matter",
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#C6105F"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "#116329"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#0550AE"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "#CF222E"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "#8250DF"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "#6F42C1"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "#E36209"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "#6B6B6B"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#D4D4D4",
          "backgroundColor": "#212121"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          },
          {
            "types": [
              "title"
            ],
            "style": {
              "color": "#569CD6",
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "property",
              "parameter"
            ],
            "style": {
              "color": "#9CDCFE"
            }
          },
          {
            "types": [
              "script"
            ],
            "style": {
              "color": "#D4D4D4"
            }
          },
          {
            "types": [
              "boolean",
              "arrow",
              "atrule",
              "tag"
            ],
            "style": {
              "color": "#569CD6"
            }
          },
          {
            "types": [
              "number",
              "color",
              "unit"
            ],
            "style": {
              "color": "#B5CEA8"
            }
          },
          {
            "types": [
              "font-matter"
            ],
            "style": {
              "color": "#CE9178"
            }
          },
          {
            "types": [
              "keyword",
              "rule"
            ],
            "style": {
              "color": "#C586C0"
            }
          },
          {
            "types": [
              "regex"
            ],
            "style": {
              "color": "#D16969"
            }
          },
          {
            "types": [
              "maybe-class-name"
            ],
            "style": {
              "color": "#4EC9B0"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "#4FC1FF"
            }
          }
        ]
      }
    },
    "image": "img/docusaurus-social-card.jpg",
    "algolia": {
      "appId": "X1Z85QJPUV",
      "apiKey": "bf7211c161e8205da2f933a02534105a",
      "indexName": "docusaurus-2",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "navbar": {
      "hideOnScroll": true,
      "title": "中国保安协会",
      "logo": {
        "alt": "",
        "src": "img/logobaidu.webp",
        "srcDark": "img/docusaurus_keytar.svg",
        "width": 32,
        "height": 32
      },
      "items": [
        {
          "to": "wu",
          "label": "城市",
          "position": "left"
        },
        {
          "to": "/learn/support",
          "label": "保安",
          "position": "left",
          "activeBaseRegex": "/learn/"
        },
        {
          "to": "showcase",
          "label": "展示",
          "position": "left"
        },
        {
          "to": "MapComponent",
          "label": "社交",
          "position": "left"
        },
        {
          "to": "/community/support",
          "label": "社区",
          "position": "left",
          "activeBaseRegex": "/community/"
        },
        {
          "to": "/google/support",
          "label": "政策",
          "position": "left",
          "activeBaseRegex": "/google/"
        },
        {
          "type": "custom-dogfood-navbar-item",
          "content": "😉",
          "position": "left"
        },
        {
          "to": "swap",
          "label": "交易",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsAfter": [
            {
              "type": "html",
              "value": "<hr style=\"margin: 0.3rem 0;\">"
            },
            {
              "href": "https://www.543x.com",
              "label": "543x"
            }
          ],
          "dropdownItemsBefore": []
        },
        {
          "href": "https://github.com/teabagging/security",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "docs",
          "items": [
            {
              "label": "Get Started",
              "href": "https://ai.543x.com"
            },
            {
              "label": "Learn React",
              "href": "https://r.543x.com"
            },
            {
              "label": "Quick Start",
              "href": "https://e.543x.com"
            },
            {
              "label": "Logo by",
              "href": "https://www.z2.pw"
            },
            {
              "label": "web3",
              "href": "https://www.494x.com"
            },
            {
              "label": "Buddhist",
              "href": "https://www.82oo.com"
            }
          ]
        },
        {
          "title": "GitHub",
          "items": [
            {
              "label": "you",
              "href": "https://c.543x.com"
            },
            {
              "label": "GitHub",
              "href": "https://www.252x.com/"
            },
            {
              "label": "Pump",
              "href": "https://d.543x.com"
            },
            {
              "label": "Swap",
              "href": "https://s.543x.com"
            },
            {
              "label": "GoogleDocs",
              "href": "https://a.494x.com"
            },
            {
              "label": "Poetry",
              "href": "https://www.14ll.com"
            }
          ]
        },
        {
          "title": "Conduct",
          "items": [
            {
              "label": "GitHub",
              "href": "https://b.543x.com"
            },
            {
              "label": "Conduct",
              "href": "https://btc.543x.com"
            },
            {
              "label": "the Team",
              "href": "https://g.543x.com"
            },
            {
              "label": "Contributors",
              "href": "https://f.543x.com"
            },
            {
              "label": "gongkao",
              "href": "https://www.64ii.com"
            },
            {
              "label": "xinhua",
              "href": "https://a.14ll.com"
            }
          ]
        },
        {
          "title": "more",
          "items": [
            {
              "label": "Blog",
              "href": "https://d.543x.com"
            },
            {
              "label": "React Native",
              "href": "https://doge.543x.com"
            },
            {
              "label": "PEPE",
              "href": "https://pepe.543x.com"
            },
            {
              "label": "Privacy",
              "href": "https://no.543x.com"
            },
            {
              "label": "Type",
              "href": "https://82ii.com"
            },
            {
              "label": "Country",
              "href": "http://www.41ii.com"
            }
          ]
        },
        {
          "title": "Vite",
          "items": [
            {
              "label": "Overview",
              "href": "https://b.252x.com/"
            },
            {
              "label": "Electron",
              "href": "https://c.252x.com/"
            },
            {
              "label": "jamstack",
              "href": "https://d.252x.com/"
            },
            {
              "label": "Vite",
              "href": "https://a.252x.com/"
            },
            {
              "label": "Bible",
              "href": "https://www.82oo.com"
            },
            {
              "label": "vpn",
              "href": "https://a.1zz1.com"
            }
          ]
        }
      ],
      "logo": {
        "alt": "Meta Open Source Logo",
        "src": "/img/logobaidu.webp",
        "width": 100,
        "height": 100,
        "href": "https://www.543x.com"
      },
      "copyright": "Copyright © 2025 中国保安协会"
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onDuplicateRoutes": "warn",
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
